<script setup>
import { ref } from 'vue'
import { Circle, FileText, MessageSquare, Mic, MicOff, MonitorUp, PhoneOff, Send, Settings2, ShieldAlert, Users, Video, VideoOff } from '@lucide/vue'
import { useRouter } from 'vue-router'
import UiCard from '../../../shared/components/UiCard.vue'
import { useAuthStore } from '../../../stores/auth'

const router = useRouter()
const auth = useAuthStore()
const inLobby = ref(true)
const denied = ref(false)
const mic = ref(true)
const cam = ref(true)
const recording = ref(true)
const rightTab = ref('stt')
const chatInput = ref('')
const chat = ref([{ who: '박서연', text: '회의록 공유 부탁드려요!' }, { who: '정도현', text: '안건 자료 채팅에 올렸습니다.' }])
const participants = [{ name: '이지연', role: 'host', speaking: true }, { name: '박서연' }, { name: '정도현' }, { name: '김민수' }, { name: '최정훈' }]
const transcript = [{ t: '13:42:08', who: '이지연', text: '오늘 안건은 Q2 캠페인 일정 확정과 예산 재분배입니다.' }, { t: '13:42:31', who: '박서연', text: '디자인 리소스 일정은 5월 마지막 주에 마무리됩니다.' }, { t: '13:43:02', who: '정도현', text: '광고 채널별 분배안은 A안을 추천합니다.' }]
function send() { if (chatInput.value.trim()) { chat.value.push({ who: auth.user?.name ?? '나', text: chatInput.value.trim() }); chatInput.value = '' } }
</script>

<template>
  <div v-if="denied" class="grid min-h-[calc(100vh-3.5rem)] place-items-center p-6"><UiCard class="max-w-md p-8 text-center"><ShieldAlert class="mx-auto h-10 w-10 text-destructive" /><h2 class="mt-4 text-lg font-semibold">입장 권한이 없습니다</h2><p class="mt-2 text-[13px] text-muted-foreground">초대된 참석자만 회의에 입장할 수 있습니다.</p><button class="mt-5 h-9 rounded-md bg-navy px-4 text-[13px] text-navy-foreground" @click="denied = false">돌아가기</button></UiCard></div>
  <div v-else-if="inLobby" class="mx-auto max-w-3xl p-6 lg:p-10">
    <UiCard class="overflow-hidden"><header class="border-b border-border px-6 py-4"><h2 class="text-[15px] font-semibold">화상회의 입장 준비</h2><p class="text-[12px] text-muted-foreground">Q2 캠페인 킥오프 · 진행 중</p></header><div class="grid gap-6 p-6 md:grid-cols-2"><div class="relative grid aspect-video place-items-center overflow-hidden rounded-lg bg-navy"><span v-if="cam" class="grid h-20 w-20 place-items-center rounded-full bg-primary text-2xl font-semibold text-primary-foreground">{{ auth.user?.avatar }}</span><span v-else class="text-white/40">카메라 꺼짐</span><div class="absolute bottom-3 flex gap-2"><button class="grid h-10 w-10 place-items-center rounded-md bg-white/10 text-white" @click="mic = !mic"><component :is="mic ? Mic : MicOff" class="h-4 w-4" /></button><button class="grid h-10 w-10 place-items-center rounded-md bg-white/10 text-white" @click="cam = !cam"><component :is="cam ? Video : VideoOff" class="h-4 w-4" /></button></div></div><div class="space-y-4"><label v-for="[label, model] in [['회의 녹음', recording], ['실시간 STT', true], ['입장 시 카메라 ON', cam]]" :key="label" class="flex items-center justify-between text-[13px]"><span>{{ label }}</span><span class="h-6 w-10 rounded-full bg-primary p-0.5"><i class="block h-5 w-5 translate-x-4 rounded-full bg-white" /></span></label><button class="h-10 w-full rounded-md bg-primary text-[13px] text-primary-foreground" @click="inLobby = false">회의 입장</button><button class="w-full text-[11px] text-muted-foreground" @click="denied = true">권한이 없는 사용자로 시뮬레이션</button></div></div></UiCard>
  </div>
  <div v-else class="fixed inset-0 z-40 flex bg-zinc-950 text-white">
    <div class="flex min-w-0 flex-1 flex-col"><header class="flex h-12 items-center justify-between border-b border-white/10 bg-zinc-900 px-4 text-[13px]"><span>Q2 캠페인 킥오프 <em v-if="recording" class="ml-3 not-italic text-red-400">REC</em></span><span class="text-white/60">01:24:08</span></header><div class="grid min-h-0 flex-1 auto-rows-fr grid-cols-2 gap-2 p-3 lg:grid-cols-3"><div v-for="(person, index) in participants" :key="person.name" :class="[index === 0 ? 'lg:col-span-2 lg:row-span-2' : '', person.speaking ? 'ring-2 ring-primary' : '']" class="relative overflow-hidden rounded-lg bg-zinc-800"><span class="absolute inset-0 grid place-items-center"><b class="grid h-16 w-16 place-items-center rounded-full bg-primary/80 text-xl">{{ person.name[0] }}</b></span><span class="absolute bottom-2 left-2 rounded bg-black/60 px-2 py-1 text-[11px]">{{ person.name }}</span></div></div><footer class="flex h-16 items-center justify-center gap-2 border-t border-white/10 bg-zinc-900"><button class="grid h-10 w-10 place-items-center rounded-md bg-white/10" @click="mic = !mic"><component :is="mic ? Mic : MicOff" class="h-4 w-4" /></button><button class="grid h-10 w-10 place-items-center rounded-md bg-white/10" @click="cam = !cam"><component :is="cam ? Video : VideoOff" class="h-4 w-4" /></button><button class="inline-flex h-10 items-center gap-2 rounded-md bg-white/10 px-4 text-[12.5px]"><MonitorUp class="h-4 w-4" /> 화면 공유</button><button class="inline-flex h-10 items-center gap-2 rounded-md bg-red-500/20 px-4 text-[12.5px] text-red-300" @click="recording = !recording"><Circle class="h-3.5 w-3.5" /> 녹음</button><button class="grid h-10 w-10 place-items-center rounded-md bg-white/10"><Settings2 class="h-4 w-4" /></button><button class="inline-flex h-10 items-center gap-2 rounded-md bg-red-600 px-4 text-[12.5px]" @click="router.push('/app/recordings')"><PhoneOff class="h-4 w-4" /> 회의 종료</button></footer></div>
    <aside class="flex w-[340px] shrink-0 flex-col border-l border-white/10 bg-zinc-900"><div class="grid grid-cols-3 border-b border-white/10"><button v-for="[id,label,icon] in [['stt','STT 요약',FileText],['people','참석자',Users],['chat','채팅',MessageSquare]]" :key="id" :class="rightTab === id ? 'border-primary text-white' : 'border-transparent text-white/50'" class="inline-flex h-11 items-center justify-center gap-1 border-b-2 text-[12px]" @click="rightTab = id"><component :is="icon" class="h-3.5 w-3.5" />{{ label }}</button></div><div v-if="rightTab === 'stt'" class="flex-1 space-y-3 overflow-y-auto p-4 text-[12px]"><h3 class="uppercase tracking-wider text-white/40">실시간 자막</h3><div v-for="line in transcript" :key="line.t"><p class="text-primary">{{ line.who }} <span class="text-white/50">{{ line.t }}</span></p><p class="text-white/85">{{ line.text }}</p></div></div><div v-else-if="rightTab === 'people'" class="p-3"><div v-for="person in participants" :key="person.name" class="flex items-center gap-2 rounded-md p-2 hover:bg-white/5"><b class="grid h-8 w-8 place-items-center rounded-full bg-white/10">{{ person.name[0] }}</b><span>{{ person.name }}</span></div></div><div v-else class="flex min-h-0 flex-1 flex-col"><div class="flex-1 space-y-3 overflow-y-auto p-3"><div v-for="message in chat" :key="`${message.who}-${message.text}`"><p class="text-[10.5px] text-white/50">{{ message.who }}</p><p class="inline-block rounded-md bg-white/10 px-2.5 py-1.5 text-[12px]">{{ message.text }}</p></div></div><div class="flex gap-1.5 border-t border-white/10 p-2.5"><input v-model="chatInput" class="h-9 flex-1 rounded-md bg-white/10 px-3 text-[12.5px]" placeholder="메시지 입력" @keydown.enter="send" /><button class="grid h-9 w-9 place-items-center rounded-md bg-primary" @click="send"><Send class="h-4 w-4" /></button></div></div></aside>
  </div>
</template>
