<script setup>
import { computed, ref } from 'vue'
import { Pencil, Plus, Search, Trash2, X } from '@lucide/vue'
import PageHeader from '../../../shared/components/PageHeader.vue'
import UiBadge from '../../../shared/components/UiBadge.vue'
import UiCard from '../../../shared/components/UiCard.vue'
import { MEMBERS } from '../../../shared/api/mock-data'
const list = ref(MEMBERS.map((item) => ({ ...item })))
const filter = ref('전체')
const query = ref('')
const editing = ref(null)
const form = ref({})
const filtered = computed(() => list.value.filter((item) => (filter.value === '전체' || item.status === filter.value) && `${item.name}${item.email}${item.dept}`.toLowerCase().includes(query.value.toLowerCase())))
function edit(member = {}) { editing.value = member; form.value = { name: '', email: '', dept: '프로덕트팀', position: '사원', role: 'User', status: '활성', ...member } }
function save() { if (!form.value.name.trim()) return; const payload = { ...form.value, id: form.value.id ?? `u-${Date.now()}` }; list.value = form.value.id ? list.value.map((item) => item.id === payload.id ? payload : item) : [...list.value, payload]; editing.value = null }
function remove(member) { if (confirm(`${member.name}을(를) 삭제하시겠어요?`)) list.value = list.value.filter((item) => item.id !== member.id) }
</script>
<template>
  <div class="mx-auto max-w-[1400px] p-6 lg:p-8"><PageHeader title="회원 관리" description="사용자 계정, 부서·직급, 활성 상태를 관리합니다."><template #action><button class="inline-flex h-9 items-center gap-1 rounded-md bg-primary px-3.5 text-[13px] text-primary-foreground" @click="edit()"><Plus class="h-3.5 w-3.5" /> 회원 추가</button></template></PageHeader><UiCard class="scroll-table"><div class="flex flex-wrap gap-2 border-b p-3"><label class="relative flex-1 max-w-sm"><Search class="absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground" /><input v-model="query" class="h-9 w-full rounded-md border pl-8 pr-3 text-[12.5px]" placeholder="이름, 이메일, 부서 검색" /></label><button v-for="item in ['전체','활성','비활성']" :key="item" :class="filter === item ? 'bg-navy text-navy-foreground' : 'border'" class="h-9 rounded-md px-3 text-[12.5px]" @click="filter = item">{{ item }}</button></div><table class="w-full text-[12.5px]"><tr class="bg-muted/40 text-muted-foreground"><th v-for="head in ['이름','이메일','부서','직급','권한','상태','액션']" :key="head" class="px-5 py-2.5 text-left font-medium">{{ head }}</th></tr><tr v-for="member in filtered" :key="member.id" class="border-t hover:bg-muted/30"><td class="px-5 py-3 font-medium">{{ member.name }}</td><td class="px-5 py-3 text-muted-foreground">{{ member.email }}</td><td class="px-5 py-3">{{ member.dept }}</td><td class="px-5 py-3">{{ member.position }}</td><td class="px-5 py-3"><UiBadge :tone="member.role === 'Master' ? 'primary' : member.role === 'Admin' ? 'navy' : 'muted'">{{ member.role }}</UiBadge></td><td class="px-5 py-3"><UiBadge :tone="member.status === '활성' ? 'success' : 'default'">{{ member.status }}</UiBadge></td><td class="px-5 py-3"><button class="mr-2" @click="edit(member)"><Pencil class="h-3.5 w-3.5" /></button><button class="text-red-600" @click="remove(member)"><Trash2 class="h-3.5 w-3.5" /></button></td></tr></table></UiCard>
  <div v-if="editing" class="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><UiCard class="w-full max-w-md"><div class="flex justify-between border-b px-5 py-3.5"><h3 class="font-semibold">회원 정보</h3><button @click="editing = null"><X class="h-4 w-4" /></button></div><div class="space-y-3.5 p-5"><input v-model="form.name" class="inp" placeholder="이름" /><input v-model="form.email" class="inp" placeholder="이메일" /><div class="grid grid-cols-2 gap-3"><input v-model="form.dept" class="inp" /><input v-model="form.position" class="inp" /></div><div class="grid grid-cols-2 gap-3"><select v-model="form.role" class="inp"><option>User</option><option>Admin</option><option>Master</option></select><select v-model="form.status" class="inp"><option>활성</option><option>비활성</option></select></div></div><div class="flex justify-end gap-2 border-t px-5 py-3"><button class="h-9 rounded-md border px-3.5" @click="editing = null">취소</button><button class="h-9 rounded-md bg-primary px-3.5 text-primary-foreground" @click="save">저장</button></div></UiCard></div></div>
</template>
