<script setup>
import { ref } from 'vue'
import { Building2, GripVertical, Plus, Users } from '@lucide/vue'
import PageHeader from '../../../shared/components/PageHeader.vue'
import UiCard from '../../../shared/components/UiCard.vue'
const tab = ref('dept')
const departments = ref([{ name: '경영지원실', count: 8, children: ['인사팀', '재무팀'], label: '지원' }, { name: '프로덕트본부', count: 24, children: ['프로덕트팀', '디자인팀', '개발팀'], label: '기술' }, { name: '전략기획팀', count: 5, children: [], label: '본사' }])
const ranks = ref([{ name: '사원', order: 1, count: 12 }, { name: '선임', order: 2, count: 8 }, { name: '책임', order: 3, count: 5 }, { name: '팀장', order: 4, count: 3 }])
function add() { if (tab.value === 'dept') departments.value.push({ name: '새 부서', count: 0, children: [], label: '본사' }); else ranks.value.push({ name: '새 직급', order: ranks.value.length + 1, count: 0 }) }
</script>
<template><div class="mx-auto max-w-[1300px] p-6 lg:p-8"><PageHeader title="조직/직급 관리" description="부서와 직급을 등록·수정·삭제합니다."><template #action><button class="inline-flex h-9 items-center gap-1 rounded-md bg-primary px-3 text-[13px] text-primary-foreground" @click="add"><Plus class="h-3.5 w-3.5" /> {{ tab === 'dept' ? '부서 추가' : '직급 추가' }}</button></template></PageHeader><div class="mb-4 flex border-b"><button v-for="[id,label] in [['dept','조직 관리'],['rank','직급 관리']]" :key="id" :class="tab === id ? 'border-primary text-primary' : 'border-transparent text-muted-foreground'" class="-mb-px h-9 border-b-2 px-4 text-[13px]" @click="tab = id">{{ label }}</button></div><div v-if="tab === 'dept'" class="grid gap-4 lg:grid-cols-3"><UiCard v-for="dept in departments" :key="dept.name" class="p-5"><div class="flex gap-2"><Building2 class="h-5 w-5 text-primary" /><div><b>{{ dept.name }}</b><p class="text-[11px] text-muted-foreground"><Users class="mr-1 inline h-3 w-3" />{{ dept.count }}명 · {{ dept.label }}</p></div></div><p v-for="child in dept.children" :key="child" class="ml-3 mt-2 border-l pl-3 text-[12.5px]">{{ child }}</p></UiCard></div><UiCard v-else class="scroll-table"><table class="w-full text-[13px]"><tr class="border-b text-muted-foreground"><th></th><th class="py-3">직급명</th><th>직급 순서</th><th>사용 인원</th></tr><tr v-for="rank in ranks" :key="rank.name" class="border-b text-center last:border-0"><td class="pl-3"><GripVertical class="h-4 w-4" /></td><td class="py-3 font-medium">{{ rank.name }}</td><td>{{ rank.order }}</td><td>{{ rank.count }}명</td></tr></table></UiCard></div></template>
